# Generated by Django 3.2 on 2023-03-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_orderlineitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='lineItem_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
    ]
