# Generated by Django 3.2 on 2023-04-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=1256, null=True)),
                ('extra_details', models.TextField(blank=True, max_length=1256, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration_weeks', models.IntegerField()),
                ('level', models.CharField(choices=[('beginner', 'Start to Swim'), ('intermediate', 'Learn to Swim'), ('advanced', 'Confident swimmers')], default='beginner', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
