# Generated by Django 3.2 on 2023-04-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Start to Swim'), ('intermediate', 'Learn to Swim'), ('advanced', 'Confident swimmers'), ('Level-1', 'Level-1'), ('Level-2', 'Level-2'), ('Level-3', 'Level-3')], default='beginner', max_length=50),
        ),
    ]
