# Generated by Django 3.2 on 2023-04-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('Level-1', 'Level-1'), ('Level-2', 'Level-2'), ('Level-3', 'Level-3')], default='beginner', max_length=50),
        ),
    ]
