# Generated by Django 3.2 on 2023-03-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='StockControl',
        ),
    ]
