# Generated by Django 3.2 on 2023-03-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230228_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(default='pp1010595de', editable=False, max_length=50, unique=True),
        ),
    ]
