# Generated by Django 3.2 on 2023-03-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_inventory_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(default='pp1011012de', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
