# Generated by Django 3.2 on 2023-03-01 14:59

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230301_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(default=products.models.Inventory.generate_sku, editable=False, max_length=50, unique=True),
        ),
    ]
